name: Backend
run-name: ¡Desplegando Backend!

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set Maven Version
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - name: Build with Maven
      run: mvn -B package --file /home/ubuntu/actions-runner/_work/GA-J17/GA-J17/pom.xml
      env:
        nombre: ${{ secrets.NOMBRE }}
        apellido: ${{ vars.APELLIDO }}
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/actions-runner/_work/GA-J17/GA-J17/target/ga-0.0.1-SNAPSHOT.jar &
